services:
  db1:
    image: mysql:8.0
    container_name: drs_db1
    environment:
      # Koristi varijablu iz .env, ako je nema stavi 'root'
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: auth_db
      TZ: Europe/Belgrade
    ports:
      - "3307:3306"
    networks:
      - drs_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db2:
    image: mysql:8.0
    container_name: drs_db2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: flights_db
      TZ: Europe/Belgrade
    ports:
      - "3308:3306"
    networks:
      - drs_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: drs_redis
    networks:
      - drs_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: drs_server
    # Uƒçitava SVE iz tvog .env fajla direktno u OS environment kontejnera
    env_file:
      - .env
    environment:
      - TZ=Europe/Belgrade
    volumes:
      - ./server:/app
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      db1:
        condition: service_healthy
    networks:
      - drs_network

  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile.dev
    container_name: drs_flight_service
    env_file:
      - .env
    environment:
      - TZ=Europe/Belgrade
    volumes:
      - ./flight-service:/app
    ports:
      - "${FLIGHT_PORT}:${FLIGHT_PORT}"
    depends_on:
      db2:
        condition: service_healthy
    networks:
      - drs_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: drs_client
    environment:
      - TZ=Europe/Belgrade
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - drs_network

networks:
  drs_network:
    driver: bridge