name: Build and Push Backend
on:
  push:
    branches: [main]
    paths: ['server/**', 'flight-service/**'] # Pokreće se samo ako menjaš backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Dozvola za GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Flight Service
        uses: docker/build-push-action@v5
        with:
          context: ./flight-service
          file: ./flight-service/Dockerfile.prod # PUTANJA DO TVOG FAJLA
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/flight-service:latest

      - name: Deploy to Render
        run: curl -X GET ${{ secrets.RENDER_BACKEND_HOOK }}