name: Build and Push Backend

on:
  push:
    branches: [main]
    paths: ['server/**', 'flight-service/**']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: katarina37
          password: ${{ secrets.GITHUB_TOKEN }}

      # PRVI SERVIS: Flight Service
      - name: Build and Push Flight Service
        uses: docker/build-push-action@v5
        with:
          context: ./flight-service
          file: ./flight-service/.prod
          push: true
          tags: ghcr.io/katarina37/flight-service:latest

      # DRUGI SERVIS: Server
      - name: Build and Push Server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/.prod
          push: true
          tags: ghcr.io/katarina37/moj-server:latest

      # AKTIVACIJA RENDERA (Dva odvojena poziva)
      - name: Deploy Flight Service
        run: curl -X GET ${{ secrets.RENDER_FLIGHT_DEPLOY_HOOK }}
      
      - name: Deploy Server
        run: curl -X GET ${{ secrets.RENDER_SERVER_DEPLOY_HOOK }}